### ISSUE TITLE
填坑项目部——小段占坑来此回复报道

### ISSUE THREAD

**Issue by inkydragon** [inkydragon/Reverse-Engineering-for-Beginners-CHS#3]
这个issue用来放**小段翻译**占坑声明。回复即可，以免重复劳动。
**整章节/大段翻译，自己开issue占坑**，遇到困难也好提出来，大家讨论。

回复时带上段落的编号。没有编号的四级标题，带上前一级的编号+标题名
`12 /
13.6 /
12.3.2 #### 四级小标题`

坑主基本每天都会上github看一看，但是合并进度可能有点慢，小段的还好，大段目前的先合并到dev分支上，让大家一起看一看核对一下，然后合并到主分支上。

有好的建建议，请新开issue讨论

**Comment by veficos** [comment]
哥们，我的分支上有做了一些更新，你可以合并之后再继续分类。

还有看看能不能及时归并到我的分支上，这样其他小伙伴也可以看到进度。

**Comment by inkydragon** [comment]
@veficos 

# 关于英文版的变动(Part I~III)

（有些章节可能是变动太大我没找到）

> 新增的章节：2、11、16、20、28、29、30~34、36、38~42、45~48、52
> 移动/删除了的章节： 13—>15、14 —>41、25—>35、26—>44、27—>48、28—>49、29—>50、30—>53

# 我的想法

最初我是这样想的：由于英文版变动较大，就算只更新目录结构，pull request 看起来就是一半红、一半绿，完全看不出翻译内容的变化，这样就显的很混乱。

考虑到龙大可能因此不同意更改目录结构，但我又很想跟上英文版的进度，所以我开了个新仓库。想等目录更新完后（翻译内容不做改动），再转让这个仓库，然后再继续完成翻译更新。这样在git上看起来就不那么混乱。

现在既然龙大想最终合并到wooyun的主仓库里，（不知道你和龙大说过没有：我们改动了目录结构，这看上去和覆盖一样），那就等我更新完目录+同步你那边的翻译更新后，再合并到你的分支里。

# 进度

我预估还有2~3天（最坑不会超过一周）我可以更新完目录。

**Comment by veficos** [comment]
@inkydragon 可以，目录这块的变更完全没问题，包括对文章进行大幅度的修改和调整都可以。但是因为后续可能加上其它格式的支持，所以我想把这个放到markdown单独一个文件夹当中。

我和龙哥商量过的。
